# Generated by Django 3.2.18 on 2023-05-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_categorie_produit_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='promotion',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
