# Generated by Django 3.2.18 on 2023-05-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230505_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
    ]
