# Generated by Django 3.2.18 on 2023-05-05 23:09

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.upload_to),
        ),
    ]
